package services

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/costrict/costrict-web/server/internal/database"
	"github.com/costrict/costrict-web/server/internal/llm"
	"github.com/costrict/costrict-web/server/internal/models"
	"github.com/google/uuid"
	"gorm.io/datatypes"
)

// GenerateService handles skill generation using LLM
type GenerateService struct {
	llmClient   *llm.Client
	indexerSvc  *IndexerService
}

// NewGenerateService creates a new generate service
func NewGenerateService(llmClient *llm.Client, indexerSvc *IndexerService) *GenerateService {
	return &GenerateService{
		llmClient:  llmClient,
		indexerSvc: indexerSvc,
	}
}

// GenerateRequest represents a skill generation request
type GenerateRequest struct {
	Prompt      string `json:"prompt" binding:"required"`
	Context     string `json:"context"`
	ItemType    string `json:"itemType"`    // Optional: specify type
	Category    string `json:"category"`    // Optional: specify category
	RegistryID  string `json:"registryId"`  // Optional: target registry
	CreatedBy   string `json:"createdBy"`   // Required: creator ID
	SaveItem    bool   `json:"saveItem"`    // Whether to save the generated item
}

// GenerateResponse represents a skill generation response
type GenerateResponse struct {
	Generated *llm.GeneratedSkill `json:"generated"`
	Item      *models.CapabilityItem `json:"item,omitempty"`
	Analysis  *llm.SkillAnalysis `json:"analysis,omitempty"`
}

// GenerateSkill generates a skill definition based on user prompt
func (s *GenerateService) GenerateSkill(ctx context.Context, req GenerateRequest) (*GenerateResponse, error) {
	// Build context with optional constraints
	contextStr := req.Context
	if req.ItemType != "" {
		contextStr += fmt.Sprintf("\nPreferred item type: %s", req.ItemType)
	}
	if req.Category != "" {
		contextStr += fmt.Sprintf("\nPreferred category: %s", req.Category)
	}

	// Build prompts
	systemPrompt, userPrompt := llm.BuildSkillGeneratePrompt(req.Prompt, contextStr)

	// Call LLM
	response, err := s.llmClient.ChatSimple(systemPrompt, userPrompt)
	if err != nil {
		return nil, fmt.Errorf("failed to generate skill: %w", err)
	}

	// Parse response
	generated, err := llm.ParseGeneratedSkill(response)
	if err != nil {
		return nil, fmt.Errorf("failed to parse generated skill: %w", err)
	}

	result := &GenerateResponse{
		Generated: generated,
	}

	// Optionally save the item
	if req.SaveItem {
		item, err := s.saveGeneratedItem(generated, req)
		if err != nil {
			return nil, fmt.Errorf("failed to save generated item: %w", err)
		}
		result.Item = item

		// Index the new item asynchronously
		go func() {
			bgCtx := context.Background()
			_ = s.indexerSvc.IndexItem(bgCtx, item)
		}()
	}

	return result, nil
}

// saveGeneratedItem saves a generated skill as a capability item
func (s *GenerateService) saveGeneratedItem(generated *llm.GeneratedSkill, req GenerateRequest) (*models.CapabilityItem, error) {
	// Determine registry ID
	registryID := req.RegistryID
	if registryID == "" {
		// Use public registry as default
		registryID = getPublicRegistryID()
	}

	// Generate slug if not provided
	slug := generated.Slug
	if slug == "" {
		slug = slugify(generated.Name)
	}

	// Build metadata
	metadata := map[string]interface{}{
		"tags":          generated.Metadata.Tags,
		"examples":      generated.Metadata.Examples,
		"prerequisites": generated.Metadata.Prerequisites,
		"generated":     true,
		"generation_prompt": req.Prompt,
	}
	metadataJSON, _ := json.Marshal(metadata)

	// Determine item type
	itemType := generated.ItemType
	if itemType == "" {
		itemType = "skill"
	}

	// Create item
	item := &models.CapabilityItem{
		ID:          uuid.New().String(),
		RegistryID:  registryID,
		Slug:        slug,
		ItemType:    itemType,
		Name:        generated.Name,
		Description: generated.Description,
		Category:    generated.Category,
		Version:     generated.Metadata.Version,
		Content:     generated.Content,
		Metadata:    datatypes.JSON(metadataJSON),
		Visibility:  "public",
		Status:      "active",
		CreatedBy:   req.CreatedBy,
	}

	db := database.GetDB()
	if result := db.Create(item); result.Error != nil {
		return nil, result.Error
	}

	// Create initial version
	version := &models.CapabilityVersion{
		ID:        uuid.New().String(),
		ItemID:    item.ID,
		Version:   1,
		Content:   item.Content,
		Metadata:  datatypes.JSON(metadataJSON),
		CommitMsg: "Generated by AI",
		CreatedBy: item.CreatedBy,
	}
	db.Create(version)

	return item, nil
}

// AnalyzeSkill analyzes an existing skill and suggests improvements
func (s *GenerateService) AnalyzeSkill(ctx context.Context, itemID string) (*llm.SkillAnalysis, error) {
	db := database.GetDB()

	var item models.CapabilityItem
	result := db.First(&item, "id = ?", itemID)
	if result.Error != nil {
		return nil, fmt.Errorf("item not found: %w", result.Error)
	}

	// Build prompts
	systemPrompt, userPrompt := llm.BuildSkillImprovePrompt(
		item.Name,
		item.ItemType,
		item.Description,
		item.Content,
		string(item.Metadata),
	)

	// Call LLM
	response, err := s.llmClient.ChatSimple(systemPrompt, userPrompt)
	if err != nil {
		return nil, fmt.Errorf("failed to analyze skill: %w", err)
	}

	// Parse response
	analysis, err := llm.ParseSkillAnalysis(response)
	if err != nil {
		return nil, fmt.Errorf("failed to parse analysis: %w", err)
	}

	return analysis, nil
}

// ImproveSkill applies suggested improvements to a skill
func (s *GenerateService) ImproveSkill(ctx context.Context, itemID string, improvements []llm.SkillImprovement, updatedBy string) (*models.CapabilityItem, error) {
	db := database.GetDB()

	var item models.CapabilityItem
	result := db.First(&item, "id = ?", itemID)
	if result.Error != nil {
		return nil, fmt.Errorf("item not found: %w", result.Error)
	}

	// Apply improvements
	for _, imp := range improvements {
		switch imp.Field {
		case "description":
			item.Description = imp.Suggested
		case "content":
			item.Content = imp.Suggested
		}
	}

	item.UpdatedBy = updatedBy

	// Save changes
	if result := db.Save(&item); result.Error != nil {
		return nil, result.Error
	}

	// Re-index the item
	go func() {
		_ = s.indexerSvc.IndexItem(context.Background(), &item)
	}()

	return &item, nil
}

// getPublicRegistryID returns the public registry ID
func getPublicRegistryID() string {
	// This should match the PublicRegistryID in handlers
	return "00000000-0000-0000-0000-000000000001"
}

// slugify converts a name to a slug
func slugify(name string) string {
	result := make([]byte, 0, len(name))
	prevDash := false
	for i := 0; i < len(name); i++ {
		c := name[i]
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') {
			result = append(result, c)
			prevDash = false
		} else if c >= 'A' && c <= 'Z' {
			result = append(result, c+32)
			prevDash = false
		} else if !prevDash && len(result) > 0 {
			result = append(result, '-')
			prevDash = true
		}
	}
	if len(result) > 0 && result[len(result)-1] == '-' {
		result = result[:len(result)-1]
	}
	return string(result)
}
