// Package app wires cs-user's HTTP routes into a gin router.
//
// Extracted from cmd/api/main.go so HTTP handler behaviour can be tested
// without starting a real TCP listener (httptest.NewRecorder + NewRouter).
package app

import (
	"net/http"

	"github.com/costrict/costrict-web/cs-user/internal/config"
	"github.com/costrict/costrict-web/cs-user/internal/middleware"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// ReadyChecker returns nil when cs-user is ready to serve traffic (DB up,
// migrations applied, etc). Phase 1 P0-1 leaves it as a stub — wired in P0-2
// when the Postgres connection lands.
type ReadyChecker interface {
	Ready() error
}

// NewRouter builds the gin engine with all cs-user routes.
//
// Routes:
//   - GET /healthz  — liveness (always 200 once process is up)
//   - GET /readyz   — readiness (delegates to readyChecker; 503 on err)
//   - /api/internal/* — gated by X-Internal-Token (ADR D8)
//   - GET /swagger/*any — Swagger UI (serves generated spec)
func NewRouter(cfg *config.Config, readyChecker ReadyChecker) *gin.Engine {
	if cfg == nil {
		panic("app.NewRouter: nil config")
	}
	if readyChecker == nil {
		readyChecker = stubReady{}
	}

	r := gin.New()
	r.Use(gin.Recovery())

	r.GET("/healthz", healthz)
	r.GET("/readyz", readyz(readyChecker))

	// Internal endpoints — consumed by costrict-web only (shared-secret gated).
	// User CRUD handlers are registered here once P0-3 lands.
	internal := r.Group("/api/internal", middleware.RequireInternalToken(cfg.Internal.Token))
	internal.GET("/ping", PingHandler)

	// Swagger UI. The spec is generated by `make swagger` (swag init) and
	// registered globally via the blank import of cs-user/docs in main.go.
	// Without that blank import the UI loads but shows an empty spec.
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}

// healthz godoc
//
//	@Summary		Liveness probe
//	@Description	Always returns 200 once the process is up. Unauthenticated — safe for K8s livenessProbe.
//	@Tags			health
//	@Produce		json
//	@Success		200	{object}	object{status=string}
//	@Router			/healthz [get]
func healthz(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

// readyz godoc
//
//	@Summary		Readiness probe
//	@Description	Returns 200 when the readiness checker (Postgres ping in P0-2) passes; 503 otherwise. Unauthenticated — safe for K8s readinessProbe. The handler is built by a factory bound to the supplied checker; swag uses the @Router path to register this endpoint.
//	@Tags			health
//	@Produce		json
//	@Success		200	{object}	object{status=string}
//	@Failure		503	{object}	object{status=string,error=string}
//	@Router			/readyz [get]
func readyz(check ReadyChecker) gin.HandlerFunc {
	return func(c *gin.Context) {
		if err := check.Ready(); err != nil {
			c.JSON(http.StatusServiceUnavailable, gin.H{"status": "not-ready", "error": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	}
}

// PingHandler godoc
//
//	@Summary		Internal handshake
//	@Description	Returns pong. Used by costrict-web to verify the X-Internal-Token handshake at startup. Requires the shared secret.
//	@Tags			internal
//	@Produce		json
//	@Security		InternalToken
//	@Success		200	{object}	object{pong=boolean}
//	@Failure		401	{object}	object{error=string}
//	@Failure		500	{object}	object{error=string}
//	@Router			/api/internal/ping [get]
func PingHandler(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"pong": true})
}

// stubReady is the default when no DB checker is wired. It returns nil
// (HTTP layer is ready). Phase 1 P0-2 replaces it with a real Postgres ping.
type stubReady struct{}

func (stubReady) Ready() error { return nil }
