// Package app wires cs-user's HTTP routes into a gin router.
//
// Extracted from cmd/api/main.go so HTTP handler behaviour can be tested
// without starting a real TCP listener (httptest.NewRecorder + NewRouter).
package app

import (
	"errors"
	"net/http"

	"github.com/costrict/costrict-web/cs-user/internal/config"
	"github.com/costrict/costrict-web/cs-user/internal/handlers"
	"github.com/costrict/costrict-web/cs-user/internal/middleware"
	"github.com/costrict/costrict-web/cs-user/internal/models"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// ReadyChecker returns nil when cs-user is ready to serve traffic (DB up,
// migrations applied, etc). Phase 1 P0-2 wires a real Postgres ping here.
type ReadyChecker interface {
	Ready() error
}

// Deps bundles the optional services NewRouter can wire. Each field is
// optional; a nil field yields a stub handler that returns HTTP 503, so the
// swagger spec stays consistent across deployments while letting unit tests
// construct a minimal router without spinning up real services.
type Deps struct {
	ReadyChecker   ReadyChecker
	Users          handlers.UserService
	AuthIdentities handlers.AuthIdentityService
}

// NewRouter builds the gin engine with all cs-user routes.
//
// Routes:
//   - GET /healthz  — liveness (always 200 once process is up)
//   - GET /readyz   — readiness (delegates to deps.ReadyChecker; 503 on err)
//   - /api/internal/* — gated by X-Internal-Token (ADR D8)
//   - GET /swagger/*any — Swagger UI (serves generated spec)
func NewRouter(cfg *config.Config, deps Deps) *gin.Engine {
	if cfg == nil {
		panic("app.NewRouter: nil config")
	}
	if deps.ReadyChecker == nil {
		deps.ReadyChecker = stubReady{}
	}

	r := gin.New()
	r.Use(gin.Recovery())

	r.GET("/healthz", healthz)
	r.GET("/readyz", readyz(deps.ReadyChecker))

	// Internal endpoints — consumed by costrict-web only (shared-secret gated).
	internal := r.Group("/api/internal", middleware.RequireInternalToken(cfg.Internal.Token))
	internal.GET("/ping", PingHandler)
	registerUserRoutes(internal, deps)
	registerAuthIdentityRoutes(internal, deps)

	// Swagger UI. The spec is generated by `make swagger` (swag init) and
	// registered globally via the blank import of cs-user/docs in main.go.
	// Without that blank import the UI loads but shows an empty spec.
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}

// registerUserRoutes wires GET /users/* endpoints. When deps.Users is nil
// (e.g. unit tests that only exercise health/ping), routes resolve to a
// 503 stub so the path always exists in the swagger spec.
func registerUserRoutes(rg *gin.RouterGroup, deps Deps) {
	usersAPI := handlers.UsersAPI{Svc: deps.Users}
	if deps.Users == nil {
		usersAPI.Svc = unavailableUserService{}
	}

	users := rg.Group("/users")
	users.GET("/:subject_id", usersAPI.GetUser)
	users.POST("/by-ids", usersAPI.GetUsersByIDs)
	users.GET("/search", usersAPI.SearchUsers)
}

// registerAuthIdentityRoutes wires GET /users/:subject_id/auth-identities.
func registerAuthIdentityRoutes(rg *gin.RouterGroup, deps Deps) {
	api := handlers.AuthIdentitiesAPI{Svc: deps.AuthIdentities}
	if deps.AuthIdentities == nil {
		api.Svc = unavailableAuthIdentityService{}
	}

	// Register on the same /users group so the path is /users/:subject_id/auth-identities.
	// gin doesn't allow redeclaring the group name, so mount via inline group.
	rg.GET("/users/:subject_id/auth-identities", api.ListIdentities)
}

// healthz godoc
//
//	@Summary		Liveness probe
//	@Description	Always returns 200 once the process is up. Unauthenticated — safe for K8s livenessProbe.
//	@Tags			health
//	@Produce		json
//	@Success		200	{object}	object{status=string}
//	@Router			/healthz [get]
func healthz(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

// readyz godoc
//
//	@Summary		Readiness probe
//	@Description	Returns 200 when the readiness checker (Postgres ping in P0-2) passes; 503 otherwise. Unauthenticated — safe for K8s readinessProbe. The handler is built by a factory bound to the supplied checker; swag uses the @Router path to register this endpoint.
//	@Tags			health
//	@Produce		json
//	@Success		200	{object}	object{status=string}
//	@Failure		503	{object}	object{status=string,error=string}
//	@Router			/readyz [get]
func readyz(check ReadyChecker) gin.HandlerFunc {
	return func(c *gin.Context) {
		if err := check.Ready(); err != nil {
			c.JSON(http.StatusServiceUnavailable, gin.H{"status": "not-ready", "error": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	}
}

// PingHandler godoc
//
//	@Summary		Internal handshake
//	@Description	Returns pong. Used by costrict-web to verify the X-Internal-Token handshake at startup. Requires the shared secret.
//	@Tags			internal
//	@Produce		json
//	@Security		InternalToken
//	@Success		200	{object}	object{pong=boolean}
//	@Failure		401	{object}	object{error=string}
//	@Failure		500	{object}	object{error=string}
//	@Router			/api/internal/ping [get]
func PingHandler(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"pong": true})
}

// stubReady is the default when no DB checker is wired. It returns nil
// (HTTP layer is ready). Phase 1 P0-2 replaces it with a real Postgres ping.
type stubReady struct{}

func (stubReady) Ready() error { return nil }

// unavailableUserService is the fallback when Deps.Users is nil — keeps the
// swagger spec stable across configurations by making the route exist but
// refuse traffic.
type unavailableUserService struct{}

func (unavailableUserService) GetUserByID(string) (*models.User, error) {
	return nil, errServiceUnavailable
}
func (unavailableUserService) GetUsersByIDs([]string) (map[string]*models.User, error) {
	return nil, errServiceUnavailable
}
func (unavailableUserService) SearchUsers(string, int) ([]*models.User, error) {
	return nil, errServiceUnavailable
}

type unavailableAuthIdentityService struct{}

func (unavailableAuthIdentityService) ListIdentities(string) ([]*models.UserAuthIdentity, error) {
	return nil, errServiceUnavailable
}

var errServiceUnavailable = errors.New("user service not configured")
