package app

import (
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/costrict/costrict-web/cs-user/internal/config"
	"github.com/gin-gonic/gin"
)

func init() { gin.SetMode(gin.TestMode) }

// stubReadyErr always returns the given error from Ready().
type stubReadyErr struct{ err error }

func (s stubReadyErr) Ready() error { return s.err }

// newCfg builds the minimum valid config for tests.
func newCfg(token string) *config.Config {
	return &config.Config{
		HTTP:     config.HTTPConfig{Port: "8081", Mode: "test"},
		Internal: config.InternalConfig{Token: token},
	}
}

func TestHealthz_AlwaysOK(t *testing.T) {
	r := NewRouter(newCfg("tok"), Deps{})
	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", w.Code)
	}
	var body map[string]string
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("body unmarshal: %v (body=%s)", err, w.Body.String())
	}
	if body["status"] != "ok" {
		t.Errorf("status field = %q, want ok", body["status"])
	}
}

func TestReadyz_StubReturnsOK(t *testing.T) {
	// nil checker → stubReady → Ready() returns nil → 200
	r := NewRouter(newCfg("tok"), Deps{})
	req := httptest.NewRequest(http.MethodGet, "/readyz", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200 (stubReady always OK)", w.Code)
	}
}

func TestReadyz_FailingCheckerReturns503(t *testing.T) {
	// Simulate a real DB ping failing — readiness must reflect it.
	r := NewRouter(newCfg("tok"), Deps{ReadyChecker: stubReadyErr{err: errors.New("db down")}})
	req := httptest.NewRequest(http.MethodGet, "/readyz", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status = %d, want 503", w.Code)
	}
	if !strings.Contains(w.Body.String(), "db down") {
		t.Errorf("body = %q, want substring 'db down'", w.Body.String())
	}
}

func TestInternalRoute_MissingToken(t *testing.T) {
	r := NewRouter(newCfg("expected"), Deps{})
	req := httptest.NewRequest(http.MethodGet, "/api/internal/ping", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("status = %d, want 401", w.Code)
	}
}

func TestInternalRoute_WrongToken(t *testing.T) {
	r := NewRouter(newCfg("expected"), Deps{})
	req := httptest.NewRequest(http.MethodGet, "/api/internal/ping", nil)
	req.Header.Set("X-Internal-Token", "wrong")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("status = %d, want 401", w.Code)
	}
}

// TestInternalRoute_CorrectTokenPassesAuth verifies the auth middleware
// passes valid traffic through to the registered /ping handler.
func TestInternalRoute_CorrectTokenPassesAuth(t *testing.T) {
	r := NewRouter(newCfg("expected"), Deps{})
	req := httptest.NewRequest(http.MethodGet, "/api/internal/ping", nil)
	req.Header.Set("X-Internal-Token", "expected")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200 (auth should pass + ping handler returns 200)", w.Code)
	}
	var body map[string]bool
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("body unmarshal: %v (body=%s)", err, w.Body.String())
	}
	if !body["pong"] {
		t.Errorf("body = %s, want {\"pong\": true}", w.Body.String())
	}
}

func TestNewRouter_NilConfigPanics(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Error("NewRouter(nil, Deps{}) did not panic")
		}
	}()
	_ = NewRouter(nil, Deps{})
}

// TestSwaggerUI_RouteRegistered confirms the /swagger UI route is wired into
// the router. The spec itself is generated by `make swagger`; we don't assert
// on spec content here (swag init is the source of truth for that).
func TestSwaggerUI_RouteRegistered(t *testing.T) {
	r := NewRouter(newCfg("tok"), Deps{})
	req := httptest.NewRequest(http.MethodGet, "/swagger/index.html", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	if w.Code != http.StatusOK {
		t.Errorf("/swagger/index.html status = %d, want 200", w.Code)
	}
}
