// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/jwks": {
            "get": {
                "description": "Exposes cs-user's RSA public signing key(s) so relying parties (server) can verify cs-user-issued JWTs. Public — RFC 7517 permits; public keys aren't secrets. Returns 503 when signing is not configured (CS_USER_JWT_SIGNING_KEY_PATH unset).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jwks"
                ],
                "summary": "JWKS endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_auth.JWKS"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/ping": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Returns pong. Used by costrict-web to verify the X-Internal-Token handshake at startup. Requires the shared secret.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Internal handshake",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "pong": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/tenants/resolve-by-email": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Looks up the active tenant whose email_domains array contains the domain extracted from the supplied email. Returns slug on unique hit, candidates on ambiguity, not_found on miss. Always 200 — semantic state lives in the ` + "`" + `status` + "`" + ` field so the caller (server RPCWriter) can branch without parsing both status code and body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Resolve tenant by email domain (Try 2)",
                "parameters": [
                    {
                        "description": "Email to resolve",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.resolveByEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "candidates": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/internal_handlers.tenantCandidate"
                                    }
                                },
                                "slug": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                },
                                "tenant_id": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/apply-enterprise-mapping": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Loads tenant_configs.employment_providers for the tenant and upserts the user's employment_identities row when the login provider is enabled. Returns 200 with ` + "`" + `{\"applied\": false}` + "`" + ` when the provider is not enabled (treated as a no-op success — login must not break on tenant config); returns 200 with ` + "`" + `{\"applied\": true}` + "`" + ` when a row was written or refreshed. Malformed tenant YAML surfaces as 500 (operator-visible); missing tenant_configs row is the same as disabled (200, applied=false).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Refresh employment_identities snapshot (login hook)",
                "parameters": [
                    {
                        "description": "User + provider + optional tenant_id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.applyEnterpriseMappingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "applied": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/by-ids": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Returns a subject_id → user map. Missing IDs are silently omitted; callers compare lengths to detect partial misses. Capped at 500 IDs per request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Batch-resolve users by subject_id",
                "parameters": [
                    {
                        "description": "Subject IDs to resolve",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.byIDsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "users": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.User"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/get-or-create": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Idempotent upsert driven by the OAuth callback's parsed JWT claims. Multi-lookup strategy (external_key → universal_id → casdoor_id → sub → username). Creates a primary identity row when a new user is created.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Upsert user from JWT claims (login entry point)",
                "parameters": [
                    {
                        "description": "JWT claim payload (parsed — cs-user does not verify JWT signatures; the X-Internal-Token middleware authenticates the caller)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.JWTClaims"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/reissue-token": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Strategy (b) re-sign: server validates the Casdoor JWT, then calls this endpoint with the parsed claims + user_subject_id. cs-user loads the user's employment_identities snapshot (Phase A4), builds enterprise claims (Phase A5), signs via the configured RSA key (Phase A3), and returns the new token. cs-user does NOT re-validate the Casdoor JWT — the X-Internal-Token middleware authenticates the caller as the server, and the server has already validated the original. Returns 503 when no signing key is configured.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reissue a cs-user-signed JWT (OAuth callback takeover)",
                "parameters": [
                    {
                        "description": "Parsed Casdoor claims + user_subject_id + optional tenant_id / audience override",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.reissueTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.reissueTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/search": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Returns active users whose username / display_name / email match the keyword (LIKE %keyword%). Limit defaults to 50, capped at 200.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Search active users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (matched against username / display_name / email)",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "users": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.User"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/transfer-identity": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Account-merge primitive. Moves the identity identified by external_key to the target user. No-op if the target already owns it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Transfer an identity to another user",
                "parameters": [
                    {
                        "description": "Transfer target + identity key",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.transferIdentityRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/{subject_id}": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Returns the user record matching the given subject_id. 404 when not found. Internal-only — requires the shared secret.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user by subject_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User subject_id (stable application-level identifier)",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/{subject_id}/auth-identities": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Returns every external login identity bound to the user, ordered so the primary identity surfaces first. Empty list when the user has none.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth-identities"
                ],
                "summary": "List a user's auth identities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User subject_id",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "identities": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.UserAuthIdentity"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/{subject_id}/bind-identity": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Idempotent bind. Recovers soft-deleted identities instead of duplicating. Re-binding an explicitly-unbound identity requires options.force_rebind.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Bind an identity to a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target user subject_id",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Claims to bind + optional BindIdentityOptions",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.bindIdentityRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/users/{subject_id}/identities/{provider}": {
            "delete": {
                "security": [
                    {
                        "InternalToken": []
                    }
                ],
                "description": "Soft-deletes every identity matching the provider on the user and marks them explicitly_unbound. Refuses to unbind the user's last identity. Promotes the next best-rank identity to primary if the unbind removed the primary.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Unbind all identities for a provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User subject_id",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Provider to unbind (e.g. github, phone, idtrust)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Always returns 200 once the process is up. Unauthenticated — safe for K8s livenessProbe.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns 200 when the readiness checker (Postgres ping in P0-2) passes; 503 otherwise. Unauthenticated — safe for K8s readinessProbe. The handler is built by a factory bound to the supplied checker; swag uses the @Router path to register this endpoint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_costrict_costrict-web_cs-user_internal_auth.JWK": {
            "type": "object",
            "properties": {
                "alg": {
                    "description": "algorithm: \"RS256\"",
                    "type": "string"
                },
                "e": {
                    "description": "RSA exponent, base64url-no-pad",
                    "type": "string"
                },
                "kid": {
                    "description": "key id: RFC 7638 thumbprint",
                    "type": "string"
                },
                "kty": {
                    "description": "key type: \"RSA\"",
                    "type": "string"
                },
                "n": {
                    "description": "RSA modulus, base64url-no-pad",
                    "type": "string"
                },
                "use": {
                    "description": "public key use: \"sig\"",
                    "type": "string"
                }
            }
        },
        "github_com_costrict_costrict-web_cs-user_internal_auth.JWKS": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_auth.JWK"
                    }
                }
            }
        },
        "github_com_costrict_costrict-web_cs-user_internal_models.BindIdentityOptions": {
            "type": "object",
            "properties": {
                "force_rebind": {
                    "type": "boolean"
                }
            }
        },
        "github_com_costrict_costrict-web_cs-user_internal_models.JWTClaims": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "preferred_username": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "provider_user_id": {
                    "type": "string"
                },
                "sub": {
                    "type": "string"
                },
                "universal_id": {
                    "type": "string"
                }
            }
        },
        "github_com_costrict_costrict-web_cs-user_internal_models.User": {
            "type": "object",
            "properties": {
                "auth_provider": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "casdoor_id": {
                    "type": "string"
                },
                "casdoor_sub": {
                    "type": "string"
                },
                "casdoor_universal_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "external_key": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_login_at": {
                    "type": "string"
                },
                "last_sync_at": {
                    "type": "string"
                },
                "organization": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "provider_user_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_costrict_costrict-web_cs-user_internal_models.UserAuthIdentity": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "explicitly_unbound": {
                    "type": "boolean"
                },
                "external_key": {
                    "type": "string"
                },
                "external_subject": {
                    "type": "string"
                },
                "external_user_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_primary": {
                    "type": "boolean"
                },
                "issuer": {
                    "type": "string"
                },
                "last_login_at": {
                    "type": "string"
                },
                "organization": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "provider_user_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_subject_id": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.applyEnterpriseMappingRequest": {
            "type": "object",
            "required": [
                "provider",
                "user_subject_id"
            ],
            "properties": {
                "provider": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "user_subject_id": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.bindIdentityRequest": {
            "type": "object",
            "required": [
                "claims"
            ],
            "properties": {
                "claims": {
                    "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.JWTClaims"
                },
                "options": {
                    "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.BindIdentityOptions"
                }
            }
        },
        "internal_handlers.byIDsRequest": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "maxItems": 500,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handlers.reissueTokenRequest": {
            "type": "object",
            "required": [
                "user_subject_id"
            ],
            "properties": {
                "audience": {
                    "description": "Audience overrides the configured default. Empty slice falls back\nto JWTConfig.DefaultAudience; populated slice replaces it.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "identity": {
                    "description": "Identity carries the parsed Casdoor JWT claims. Optional — when nil,\nonly standard JWT claims + enterprise claims (if any) are emitted.\nTypical Phase A7 callers always pass Identity; the nil path exists\nfor refresh-token flows (Phase B) where identity may be cached.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_costrict_costrict-web_cs-user_internal_models.JWTClaims"
                        }
                    ]
                },
                "tenant_id": {
                    "description": "TenantID is reserved for Phase B. Phase A callers pass \"default\" or\nleave empty; the service falls back to \"default\".",
                    "type": "string"
                },
                "user_subject_id": {
                    "description": "UserSubjectID is the cs-user user's stable subject_id. Required.",
                    "type": "string"
                }
            }
        },
        "internal_handlers.reissueTokenResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.resolveByEmailRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.tenantCandidate": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.transferIdentityRequest": {
            "type": "object",
            "required": [
                "external_key",
                "target_user_subject_id"
            ],
            "properties": {
                "external_key": {
                    "type": "string"
                },
                "source_user_subject_id": {
                    "description": "SourceUserSubjectID is accepted for forwards compatibility with\nserver's signature; cs-user identifies the identity purely by\nexternal_key.",
                    "type": "string"
                },
                "target_user_subject_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "InternalToken": {
            "description": "Shared secret for service-to-service calls from costrict-web (ADR D8).",
            "type": "apiKey",
            "name": "X-Internal-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "cs-user API",
	Description:      "User identity service for the costrict-cloud platform (Phase 1: user CRUD + read-through RPC).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
