{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  db: {{ .Values.auth.database | b64enc | quote }}
{{- end }}
