apiVersion: v2
appVersion: 0.0.80
description: Costrict Web Portal - Frontend web application
maintainers:
- name: costrict
  url: https://github.com/costrict
name: costrict-web-portal
type: application
version: 0.0.80
