# Build stage
FROM golang:1.23-alpine AS builder

ARG HTTPS_PROXY
ARG HTTP_PROXY

WORKDIR /app

RUN apk add --no-cache ca-certificates git

ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

# Final stage
FROM alpine:latest

ARG HTTPS_PROXY
ARG HTTP_PROXY

RUN apk --no-cache add ca-certificates git

WORKDIR /root/

COPY --from=builder /app/worker .

CMD ["./worker"]
