{{- if .Values.nginxRouter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-headless
  namespace: {{ include "gateway.namespace" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - port: {{ .Values.nginxRouter.discovery.gatewayPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
{{- end }}
