package llm

import (
	"encoding/json"
	"fmt"
)

// GeneratedSkill represents a skill generated by the LLM
type GeneratedSkill struct {
	Name        string                 `json:"name"`
	Slug        string                 `json:"slug"`
	Description string                 `json:"description"`
	ItemType    string                 `json:"itemType"`
	Category    string                 `json:"category"`
	Content     string                 `json:"content"`
	Metadata    GeneratedSkillMetadata `json:"metadata"`
}

// GeneratedSkillMetadata contains metadata for a generated skill
type GeneratedSkillMetadata struct {
	Tags          []string `json:"tags"`
	Examples      []string `json:"examples"`
	Prerequisites []string `json:"prerequisites"`
	Version       string   `json:"version"`
}

// SkillImprovement represents a suggested improvement for a skill
type SkillImprovement struct {
	Field    string `json:"field"`
	Current  string `json:"current"`
	Suggested string `json:"suggested"`
	Reason   string `json:"reason"`
}

// SkillAnalysis represents the analysis result of a skill
type SkillAnalysis struct {
	Improvements  []SkillImprovement `json:"improvements"`
	OverallScore  int                `json:"overallScore"`
	Strengths     []string           `json:"strengths"`
	Weaknesses    []string           `json:"weaknesses"`
}

// QueryExpansion represents expanded search terms
type QueryExpansion struct {
	ExpandedTerms       []string `json:"expandedTerms"`
	Synonyms            []string `json:"synonyms"`
	RelatedConcepts     []string `json:"relatedConcepts"`
	SuggestedCategories []string `json:"suggestedCategories"`
	SearchIntent        string   `json:"searchIntent"`
}

// BehaviorPattern represents a pattern found in behavior logs
type BehaviorPattern struct {
	Type            string `json:"type"`
	Description     string `json:"description"`
	Frequency       string `json:"frequency"`
	Impact          string `json:"impact"`
	SuggestedAction string `json:"suggestedAction"`
}

// ExperienceRecommendation represents a recommendation from experience analysis
type ExperienceRecommendation struct {
	Priority string `json:"priority"`
	Action   string `json:"action"`
	Reason   string `json:"reason"`
}

// CandidateExperience represents a candidate experience from analysis
type CandidateExperience struct {
	Type         string  `json:"type"`
	Title        string  `json:"title"`
	Description  string  `json:"description"`
	Context      string  `json:"context"`
	Frequency    int     `json:"frequency"`
	ImpactScore  float64 `json:"impactScore"`
}

// ExperienceAnalysisResult represents the result of experience analysis
type ExperienceAnalysisResult struct {
	Patterns             []BehaviorPattern      `json:"patterns"`
	Recommendations      []ExperienceRecommendation `json:"recommendations"`
	CandidateExperiences []CandidateExperience  `json:"candidateExperiences"`
}

// ParseGeneratedSkill parses LLM response into GeneratedSkill
func ParseGeneratedSkill(response string) (*GeneratedSkill, error) {
	var skill GeneratedSkill
	if err := json.Unmarshal([]byte(response), &skill); err != nil {
		return nil, fmt.Errorf("failed to parse generated skill: %w", err)
	}
	return &skill, nil
}

// ParseSkillAnalysis parses LLM response into SkillAnalysis
func ParseSkillAnalysis(response string) (*SkillAnalysis, error) {
	var analysis SkillAnalysis
	if err := json.Unmarshal([]byte(response), &analysis); err != nil {
		return nil, fmt.Errorf("failed to parse skill analysis: %w", err)
	}
	return &analysis, nil
}

// ParseQueryExpansion parses LLM response into QueryExpansion
func ParseQueryExpansion(response string) (*QueryExpansion, error) {
	var expansion QueryExpansion
	if err := json.Unmarshal([]byte(response), &expansion); err != nil {
		return nil, fmt.Errorf("failed to parse query expansion: %w", err)
	}
	return &expansion, nil
}

// ParseExperienceAnalysis parses LLM response into ExperienceAnalysisResult
func ParseExperienceAnalysis(response string) (*ExperienceAnalysisResult, error) {
	var result ExperienceAnalysisResult
	if err := json.Unmarshal([]byte(response), &result); err != nil {
		return nil, fmt.Errorf("failed to parse experience analysis: %w", err)
	}
	return &result, nil
}
