package llm

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

// GeneratedSkill represents a skill generated by the LLM
type GeneratedSkill struct {
	Name        string                 `json:"name"`
	Slug        string                 `json:"slug"`
	Description string                 `json:"description"`
	ItemType    string                 `json:"itemType"`
	Category    string                 `json:"category"`
	Content     string                 `json:"content"`
	Metadata    GeneratedSkillMetadata `json:"metadata"`
}

// GeneratedSkillMetadata contains metadata for a generated skill
type GeneratedSkillMetadata struct {
	Tags          []string `json:"tags"`
	Examples      []string `json:"examples"`
	Prerequisites []string `json:"prerequisites"`
	Version       string   `json:"version"`
}

// SkillImprovement represents a suggested improvement for a skill
type SkillImprovement struct {
	Field    string `json:"field"`
	Current  string `json:"current"`
	Suggested string `json:"suggested"`
	Reason   string `json:"reason"`
}

// SkillAnalysis represents the analysis result of a skill
type SkillAnalysis struct {
	Improvements  []SkillImprovement `json:"improvements"`
	OverallScore  int                `json:"overallScore"`
	Strengths     []string           `json:"strengths"`
	Weaknesses    []string           `json:"weaknesses"`
}

// QueryExpansion represents expanded search terms
type QueryExpansion struct {
	ExpandedTerms       []string `json:"expandedTerms"`
	Synonyms            []string `json:"synonyms"`
	RelatedConcepts     []string `json:"relatedConcepts"`
	SuggestedCategories []string `json:"suggestedCategories"`
	SearchIntent        string   `json:"searchIntent"`
}

// BehaviorPattern represents a pattern found in behavior logs (kept for future use)
type BehaviorPattern struct {
	Type            string `json:"type"`
	Description     string `json:"description"`
	Frequency       string `json:"frequency"`
	Impact          string `json:"impact"`
	SuggestedAction string `json:"suggestedAction"`
}

// extractJSON extracts JSON from LLM response that may contain markdown code blocks
func extractJSON(response string) string {
	response = strings.TrimSpace(response)

	// Try to extract JSON from markdown code blocks
	// Pattern: ```json ... ``` or ``` ... ```
	re := regexp.MustCompile("(?s)```(?:json)?\\s*\\n?([\\s\\S]*?)\\n?```")
	matches := re.FindStringSubmatch(response)
	if len(matches) > 1 {
		return strings.TrimSpace(matches[1])
	}

	// If no code block, try to find JSON object directly
	// Find the first { and last }
	start := strings.Index(response, "{")
	end := strings.LastIndex(response, "}")
	if start != -1 && end != -1 && end > start {
		return response[start : end+1]
	}

	return response
}

// ParseGeneratedSkill parses LLM response into GeneratedSkill
func ParseGeneratedSkill(response string) (*GeneratedSkill, error) {
	jsonStr := extractJSON(response)
	var skill GeneratedSkill
	if err := json.Unmarshal([]byte(jsonStr), &skill); err != nil {
		return nil, fmt.Errorf("failed to parse generated skill: %w", err)
	}
	return &skill, nil
}

// ParseSkillAnalysis parses LLM response into SkillAnalysis
func ParseSkillAnalysis(response string) (*SkillAnalysis, error) {
	jsonStr := extractJSON(response)
	var analysis SkillAnalysis
	if err := json.Unmarshal([]byte(jsonStr), &analysis); err != nil {
		return nil, fmt.Errorf("failed to parse skill analysis: %w", err)
	}
	return &analysis, nil
}

// ParseQueryExpansion parses LLM response into QueryExpansion
func ParseQueryExpansion(response string) (*QueryExpansion, error) {
	jsonStr := extractJSON(response)
	var expansion QueryExpansion
	if err := json.Unmarshal([]byte(jsonStr), &expansion); err != nil {
		return nil, fmt.Errorf("failed to parse query expansion: %w", err)
	}
	return &expansion, nil
}
