apiVersion: v2
appVersion: 0.0.80
description: Costrict Web Worker - Background task processing service
maintainers:
- name: costrict
  url: https://github.com/costrict
name: costrict-web-worker
type: application
version: 0.0.80
