-- +goose Up
-- +goose StatementBegin

-- Adds short_id to users: a platform-wide compact handle derived from
-- subject_id (SHA256 truncated). Stable, non-email, used by downstream
-- systems (e.g. Gitea login) that need a short unique identifier.
-- Generated by cs-user at user creation; never recomputed.
--
-- NOT NULL without default — cs-user has no existing user rows at rollout
-- (greenfield), so the column is populated purely by the application.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS short_id VARCHAR(32) NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_short_id
    ON users (short_id)
 WHERE short_id <> '';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP INDEX IF EXISTS idx_user_short_id;
ALTER TABLE users DROP COLUMN IF EXISTS short_id;

-- +goose StatementEnd
