apiVersion: v2
appVersion: 0.0.80
description: Costrict Web API Server - Main backend service
maintainers:
- name: costrict
  url: https://github.com/costrict
name: costrict-web-api
type: application
version: 0.0.80
